#!/bin/sh

cli=/Applications/Karabiner.app/Contents/Library/bin/karabiner

$cli set general.dont_remap_non_apple_keyboard 1
/bin/echo -n .
$cli set remap.controlL2fn 1
/bin/echo -n .
$cli set remap.fn_fkeys_to_consumer_f1 1
/bin/echo -n .
$cli set remap.fn_fkeys_to_consumer_f10 1
/bin/echo -n .
$cli set remap.fn_fkeys_to_consumer_f3_lion 1
/bin/echo -n .
$cli set remap.fn_fkeys_to_consumer_f5 1
/bin/echo -n .
$cli set remap.fn_fkeys_to_consumer_f7 1
/bin/echo -n .
$cli set remap.fn2controlL 1
/bin/echo -n .
# System Peference: Delay Until Repeat: Short(est)
#$cli set repeat.initial_wait 250
#/bin/echo -n .
# System Preference: Key Repeat: Fast(est)
#$cli set repeat.wait 33
#/bin/echo -n .
/bin/echo
