#!/bin/bash
set -e

# how to refresh HEAD if it changes upstream
# git remote set-head origin -a
HEAD=$(git symbolic-ref --short refs/remotes/origin/HEAD)
merged_target="${1:-${HEAD}}"

git fetch

branches=$(git branch --merged "${merged_target}" | grep -v "^\*")
echo "${branches}" | while read branch; do
    branch_full_name=$(git rev-parse --symbolic-full-name "${branch}")
    branch_upstream=$(git for-each-ref --format='%(upstream:short)' "${branch_full_name}")
    if [ "${branch_upstream}" != "${merged_target}" ]; then
        git branch -d "${branch}"
    fi
done
